const DATA = [
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
  {
    image: "",
    status: "active",
    product: "art",
    sales: 100,
    inventory: 10,
    revenue: 10,
  },
];

export default DATA;
